### ISSUE TITLE
[Bug] 版本 3.x: 介绍页的掘金小册链接已失效

### ISSUE THREAD

**Issue by Hephaest** [NervJS/taro-docs#124]
### Summary
今天访问 Taro 3.x 介绍页的时候无意发现学习资源中的掘金小册[链接](https://juejin.cn/book/6844733744830480397?referrer=5ba228f16fb9a05d3251492d)已失效。

<img width="790" alt="Screen Shot 2023-07-16 at 4 03 35 PM" src="https://github.com/NervJS/taro-docs/assets/37981444/9e917de6-5bd0-408a-9306-64c9ac05a1f1">

#### Expected Behavior

链接可访问

**Comment by ZakaryCode** [comment]
该链接并为失效 🤔️

<img width="792" alt="image" src="https://github.com/NervJS/taro-docs/assets/24262362/b90e4697-356c-40bd-a936-aeaab0d3e8bf">
