### ISSUE TITLE
如何参与大型开源项目-Taro 共建 ，能更新下不？

### ISSUE THREAD

**Issue by luckymore** [NervJS/taro-docs#24]
https://nervjs.github.io/taro-docs/blog/2022-01-19-how-to-join-Taro

**Comment by Chen-jj** [comment]
@luckymore 文章是有哪些不清晰的地方希望改进么？

**Comment by luckymore** [comment]
@Chen-jj 看项目已经不是用yarn那一套了，新的开发流程能更新下不

**Comment by Chen-jj** [comment]
@luckymore 文档有更新的：https://docs.taro.zone/docs/codebase-overview#%E5%A6%82%E4%BD%95%E5%BC%80%E5%8F%91
