### ISSUE TITLE
”表单组件支持使用 defaultValue 设置初始值“ 这个说明在文档中没有体现

### ISSUE THREAD

**Issue by hgaogao** [NervJS/taro-docs#249]
**Describe the bug**
`表单组件支持使用 defaultValue 设置初始值` 这个说明在文档中没有体现 , `InputProps` 缺少 `defaultValue`  这个参数
这个是有意为之，还是漏了？
[Input组件](https://nervjs.github.io/taro-docs/docs/components/forms/input)

**Expected behavior**
`InputProps` 应该有 `defaultValue`  这个参数

**Screenshots**
![image](https://github.com/NervJS/taro-docs/assets/47255125/48869a54-1c6d-4a9e-b1b3-ea4e51a7f527)

**Comment by ZakaryCode** [comment]
在 4.x 文档可以找到，目前还有同步
