### ISSUE TITLE
文档 4.x 版仍未发布

### ISSUE THREAD

**Issue by ianzone** [NervJS/taro-docs#278]
当前 taro 已升级到 4.0.5，但文档还没发布正式版
<img width="245" alt="image" src="https://github.com/user-attachments/assets/c37060a7-0256-486e-b73b-76bc7d8ea784">

**Comment by hanjin001** [comment]
[taro 4 文档](https://docs.taro.zone/docs)现在已经发布了。`taro4` 和 `taro3` 文档区别不大
