### ISSUE TITLE
提供 canIuse 页面

### ISSUE THREAD

**Issue by ZakaryCode** [NervJS/taro-docs#34]
已有 [miniapp-types](https://github.com/robinv8/miniapp-types) 库，能否基于这个为文档提供一个类似于 canIuse 的页面。

@robinv8

**Comment by robinv8** [comment]
![image](https://user-images.githubusercontent.com/12277531/198288173-f52779c1-853e-4db7-b6ef-2de7d7b06aa8.png)
是这个吗？

**Comment by ZakaryCode** [comment]
嗯嗯，可以给用户一个快捷搜索的方式

**Comment by robinv8** [comment]
> 嗯嗯，可以给用户一个快捷搜索的方式

我试试

**Comment by ZakaryCode** [comment]
fix in #47
