### ISSUE TITLE
类型同步 CI 失败

### ISSUE THREAD

**Issue by ZakaryCode** [NervJS/taro-docs#35]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/24262362/198277485-714922e7-8036-40f0-af88-49fb440fa1e3.png">

[Sync Components types CI Error](https://github.com/NervJS/taro-docs/actions/runs/3301599184/jobs/5447249785)

另外间隔时间有点长，感觉可以每周一到两次，或者更频繁一点也可以

**Comment by robinv8** [comment]
我跟进下
