### ISSUE TITLE
文档链接404 bug

### ISSUE THREAD

**Issue by SetoKaiba** [NervJS/taro-docs#61]
![image](https://user-images.githubusercontent.com/159540/212475889-d6a08cb7-b274-4e3e-aa56-133db323001b.png)

从taro官网进去的文档链接是
https://taro-docs.jd.com ①
自动跳转到
https://taro-docs.jd.com/docs ②

手动输入这个链接，也可以跳到文档
https://docs.taro.zone ③
自动跳转到
https://docs.taro.zone/docs ④

此时的①②③④的基础教程的链接均指向根目录
https://taro-docs.jd.com/react-overall
https://docs.taro.zone/react-overall

手动输入②，基础教程的链接仍然指向根目录
https://taro-docs.jd.com/react-overall

手动输入④，基础教程的链接指向正确的子目录
![image](https://user-images.githubusercontent.com/159540/212475927-6bf3b016-34a3-4dbf-8837-6302c8be5b0f.png)
https://docs.taro.zone/docs/react-overall
但是左键点击的时候，还是跳转到根目录
![image](https://user-images.githubusercontent.com/159540/212475940-1fb6800d-5535-424b-96e6-daf1287999bb.png)
https://docs.taro.zone/react-overall
中键点击，打开新tab的时候，跳转到正确的子目录
https://docs.taro.zone/docs/react-overall

**Comment by AdvancedCat** [comment]
应该是左上角 Logo 点击后 location.pathbame = '/docs' ，导致页面内 './react-overall' 跳转到根目录下

正确的应该是 location.pathname = '/docs/'

**Comment by SetoKaiba** [comment]
我说的情况是没点击左上角的Logo的情况下也会。

**Comment by abitwhy** [comment]
因为缺少结尾 `/`。

**Comment by SetoKaiba** [comment]
所以会修复么，我看现在文档也还是点不进去的
