### ISSUE TITLE
API表格布局真的是太糟心了

### ISSUE THREAD

**Issue by SupermanChao** [NervJS/taro-docs#73]
![image](https://user-images.githubusercontent.com/18051214/221342154-6abc3e3f-7b84-4858-a216-6ea6f1627859.png)

使用键盘和鼠标的噩梦，想看后面的说明还得滑到表格最后一行，鼠标左右拖动好再回来，再回来的时候又忘了左边对应的是啥！
左边留的空隙太大，右边留的大还不能调节。
希望官方能优化下。nutui的组件文档就非常不错

**Comment by ZakaryCode** [comment]
Duplicate of #29
